### ISSUE TITLE
Art Checklist

### ISSUE THREAD

**Issue by Medallyon** [Medallyon/evo-game#17]
This issue may be closed when all of the following items have been completed:

- [x] Concept Art
- [x] Background Art (needs to be continuous)
  - [x] Level 1
  - [x] Level 2
  - [x] Level 3
- [x] UI
  - [x] Main Menu
    - [x] Buttons
      - [x] Play
      - [x] Scores (Optional)
      - [x] Settings (Optional)
  - [x] In-Game HUD
    - [x] Player Health
    - [x] Level Progress Bar
    - [ ] Pause Button
